Add OpenFF Docs template
lilyminium/cookiecutter-openff pull request #2
Opened 2023-04-17 12:43 UTC by Yoshanuikabundi

Changes made in this Pull Request:
 - MyST setup
 - OpenFF sphinx theme configuration
 - Intersphinx setup with all existing OpenFF tools
 - Move docs environment to devtools/conda-envs
 - Automatic API docs documentation
 - Changes to docstrings and `__all__` to demonstrate API docs setup

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [ ] CHANGELOG.md updated?
 - [ ] AUTHORS.md updated?

2023-04-18 00:13 UTC, lilyminium requested changes
Looking good, just a question about a nagl mention.

I'm not sure if there's an easy way to test out the docs -- the MDAnalysis cookiecutter pushes to a "cookie" repo as part of CI, which I could re-implement if that would be useful.

2023-04-18 00:13 UTC, lilyminium commented on {{cookiecutter.repo_name}}/docs/make.bat
> +set SPHINXPROJ=openff-nagl
Is this change on purpose?

2023-04-18 06:58 UTC, Yoshanuikabundi commented on {{cookiecutter.repo_name}}/docs/make.bat
> +set SPHINXPROJ=openff-nagl
Nope! Fixed in 7d92590

2023-04-18 07:03 UTC, Yoshanuikabundi commented
Could do the GH Pages thing and push to a branch, and then have RTD render it as a version in the cookiecutter docs? I haven't thought much about testing, since we're only going to use it internally I figure if there's an issue that can be detected by tests then all its gonna do is cause a cookie to fail when we try to create it. Not the end of the world.

This wouldn't be for this PR, but would it be helpful if I tried to get the package structure set up like OpenFF projects - ie, `openff.packagename` rather than `openff-packagename`?

2023-04-19 02:46 UTC, lilyminium approved these changes

2023-04-19 02:47 UTC, lilyminium commented
> This wouldn't be for this PR, but would it be helpful if I tried to get the package structure set up like OpenFF projects - ie, openff.packagename rather than openff-packagename?

Yes, that would be fantastic!

2023-04-19 02:48 UTC, lilyminium commented
LGTM, thank you!

2023-04-19 02:48 UTC, merged